[package]
name = "landgen"
version = "0.1.0"
authors = ["Andrey Korotaev <a.korotaev@hedgewars.org>"]

[dependencies]
integral-geometry = { path = "../integral-geometry" }
land2d = { path = "../land2d" }
