[package]
name = "hedgewars-server"
version = "0.0.1"
authors = [ "Andrey Korotaev <a.korotaev@hedgewars.org>" ]

[dependencies]
rand = "0.5"
mio = "0.6"
slab = "0.4"
netbuf = "0.4.0"
nom = "4.0"
env_logger = "0.4"
log = "0.4"
proptest = "0.8"
base64 = "0.9"
